import { z } from "zod";

export const productSchema = z.object({
  name: z.string().min(2),
  slug: z.string().min(2),
  model: z.string().min(1),
  sku: z.string().min(1),
  brandId: z.string().min(1),
  categoryId: z.string().min(1),
  shortDescription: z.string().min(5),
  description: z.string().min(10),
  price: z.coerce.number().positive(),
  oldPrice: z.coerce.number().optional(),
  costPrice: z.coerce.number().optional(),
  stock: z.coerce.number().int().min(0),
  warrantyMonths: z.coerce.number().int().min(0).default(24),
  installationAvailable: z.coerce.boolean().default(true),
  recommendedAreaMin: z.coerce.number().int().optional(),
  recommendedAreaMax: z.coerce.number().int().optional(),
  btu: z.coerce.number().int().optional(),
  kw: z.coerce.number().optional(),
  energyClass: z.string().optional(),
  inverter: z.coerce.boolean().optional(),
  mainImageUrl: z.string().optional(),
  seoTitle: z.string().optional(),
  seoDescription: z.string().optional(),
  status: z.enum(["draft", "published", "archived"]).default("draft"),
  isFeatured: z.coerce.boolean().default(false),
  isBestSeller: z.coerce.boolean().default(false),
});
